___
---

# Part I: NumPy exercises:
---

In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

## Ex. 1
Assume you have a gene expression matrix containing expression levels for N genes (in N matrix rows) in M samples (in M matrix columns). The samples can be separated in two distinct groups or contidions.
In WeBeep (materials → exercises) you will find an example file named “GSE16237_series_matrixcleaned-4noamp_vs_4amp.tsv” extracted from a publicly available data set for gene expression levels from **neuroblastoma tumors**. The file contains only a subset of the available samples and does not report sample IDs nor gene IDs (to keep this exercise as simple as possible).

Once downloaded, you can read the file as a NumPy array using the function “np.fromfile()”:

In [2]:
# pip install numpy (in terminal)
import numpy as np
ndat = np.fromfile("GSE16237_series_matrix-cleaned-4noamp_vs_4amp.tsv", dtype=float, count=-1, sep='\t').reshape(20464,8)

As you can guess from the “reshape” transformation, the file contains expression levels for 20,464
genes in 8 tumors. The first 4 samples (columns) are for stage 4 tumors which do not harbor an
amplification of the MYCN gene, the last 4 samples (columns) are from stage 4 tumors which instead
do harbor an amplification of the MYCN gene (massive increase in copy number of that gene, a
frequent event in neuroblastomas).

Tasks:
a) Perform a (dangerously simplified) column-wise normalization of the expression levels by dividing all expression levels of one sample (one column) by the maximum expression level of that column, such that for each column/sample expression levels range from 0 to 1. [This is not how such data would be normalized, but for the sake of this exercise we will consider it a sufficient approximation although it is not …]

In [3]:
for i in range(ndat.shape[1]):
    col_max = np.max(ndat[:,i])
    ndat[:,i] = ndat[:,i]/col_max

b) Then, for each of the two conditions (non-amplified stage 4 neuroblastoma versus MYCNamplified stage 4 neuroblastoma), i.e., independently for the first 4 columns and the last 4 columns, identify the row (=position in the file) of the gene with the highest mean expression across the four samples of that condition.
Hint: for finding the position (index) of a maximum value in a NumPy array, you can use the function “np.argmax()”!

In [4]:
first_half = int(ndat.shape[1]/2)
second_half = range(int(ndat.shape[1]/2), ndat.shape[1])
first_half
second_half

4

range(4, 8)

In [5]:
means_first = np.mean(ndat[:, 0:first_half], axis = 1)
first_max_mean = np.argmax(means_first, axis = 0)
first_max_mean
means_first[first_max_mean]


means_second = np.mean(ndat[:, second_half], axis = 1)
second_max_mean = np.argmax(means_second, axis = 0)
second_max_mean
means_second[second_max_mean]

7816

0.9472344118836824

7816

0.9064957172048588

---
## Ex. 2
Assume you have a 1-dimenstional NumPy array of experimental observations/measurements, where each observervation value is >= 0. You can easily construct an arbitrary example vector.
Immagine that you want to compute log10 for those observations which are >1, but want to set 0 for all those which are smaller (so you don’t get negative values or even worse, -inf when the observation was 0). Can you do this with a single command?

In [6]:
my_arr = np.array([0.005, 4.05, 100, 0.99, 0.5, 1.1], dtype = float)
my_arr

new_arr = np.where(my_arr > 1, np.log10(my_arr), 0)
new_arr

array([5.00e-03, 4.05e+00, 1.00e+02, 9.90e-01, 5.00e-01, 1.10e+00])

array([0.        , 0.60745502, 2.        , 0.        , 0.        ,
       0.04139269])

___
## Ex. 3
The following may be useful for some applications in linear algebra:
Find out how to create NumPy quadratic matrices (same number of rows and columns) which have all elements set to 0 except the values on the diagonal using one single command/function call. Create …
**(a)** A 4x4 matrix which has all diagonal values set to 1, the rest to 0.

In [7]:
np.diag(np.ones(4, dtype = int))
np.eye(4)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])


(b) A 4x4 matrix which has the diagonal values ranging from 1 to 4, all other values set to 0

In [8]:
np.diag(np.array(range(1,5), dtype=int))
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

---
## Ex. 4
Creation of N-dimensional arrays
a) Create a 2-dimensional array with 4 rows and 25 columns containing the natural numbers from 1 to 100. Use a simple command that avoids listing all 100 numbers.

In [9]:
np.array(range(1,101),dtype = int).reshape(4,25)
np.arange(100).reshape(4,25)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
         64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
         89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

b) Create the same array without specifying the number of columns in your command!

In [10]:
np.arange(1,101).reshape(4,-1)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
         64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
         89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])


c) Place the same natural numbers in a 3-dimensional array (choose the necessary number of rows, columns and layers). After having created the array, how can you obtain the number of dimensions, the shape and the content data type from the array object itself?

In [11]:
a = np.arange(1,101).reshape(10, 2, 5) # layer, row, column
a.shape
a.ndim
a[1,0,1]
a

(10, 2, 5)

3

12

array([[[  1,   2,   3,   4,   5],
        [  6,   7,   8,   9,  10]],

       [[ 11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20]],

       [[ 21,  22,  23,  24,  25],
        [ 26,  27,  28,  29,  30]],

       [[ 31,  32,  33,  34,  35],
        [ 36,  37,  38,  39,  40]],

       [[ 41,  42,  43,  44,  45],
        [ 46,  47,  48,  49,  50]],

       [[ 51,  52,  53,  54,  55],
        [ 56,  57,  58,  59,  60]],

       [[ 61,  62,  63,  64,  65],
        [ 66,  67,  68,  69,  70]],

       [[ 71,  72,  73,  74,  75],
        [ 76,  77,  78,  79,  80]],

       [[ 81,  82,  83,  84,  85],
        [ 86,  87,  88,  89,  90]],

       [[ 91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100]]])

d) Copy the array from c) into a new array and modify the copy without modifying the original array.

In [12]:
hard_copy_a = a.copy()
hard_copy_a[2,1,0] = 123
a[2,1,0]
hard_copy_a[2,1,0]

26

123

e) Compute the sum of all differences between the array from c) and the array from d). Try using the standard command “sum()” and the NumPy version “np.sum()”. Do you observe the same behavior?

In [13]:
sum(a-hard_copy_a)
np.sum(a-hard_copy_a)

array([[  0,   0,   0,   0,   0],
       [-97,   0,   0,   0,   0]])

-97

f) The array multiplication with “a*b” of two equally shaped matrices a and b multiplies elementwise the corresponding elements, so it is not a true matrix multiplication. Find out how a true matrix multiplication can be performed in NumPy and perform it by squaring the matrix obtained from a). What shape does the output have?

In [14]:
my_mat = np.arange(100).reshape(4,25)
squared_mat = np.matmul(my_mat, np.transpose(my_mat))

squared_mat.shape
squared_mat

(4, 4)

array([[  4900,  12400,  19900,  27400],
       [ 12400,  35525,  58650,  81775],
       [ 19900,  58650,  97400, 136150],
       [ 27400,  81775, 136150, 190525]])

___
## Ex. 5
The NumPy function “np.random.random(N)” generates N random numbers in the interval [0.0,1.0), i.e., without the upper boundary 1. Use a simple command to check that for N=100 indeed all returned random numbers are smaller than 1 AND at least 0.
Unfortunately performing a logical AND on NumPy arrays does not work with the standard bitwise AND operator (“&”). Can you find out how to perform a logical AND operation on two NumPy arrays?

In [15]:
import random

to_check = np.random.random(100)
to_check
np.logical_and(np.all(to_check < 1), np.any(to_check >= 0))


array([0.65160116, 0.69893276, 0.63885681, 0.55283114, 0.00151509,
       0.37707706, 0.09589841, 0.32965977, 0.69339942, 0.63108694,
       0.62234448, 0.15148226, 0.33249369, 0.30723802, 0.78428213,
       0.63763704, 0.39932385, 0.1319418 , 0.21049649, 0.29491646,
       0.24993633, 0.51915339, 0.77639953, 0.01613106, 0.3331384 ,
       0.11183348, 0.5674965 , 0.67249841, 0.34486842, 0.19523923,
       0.18438553, 0.20668713, 0.36955637, 0.47204511, 0.41188617,
       0.94693139, 0.77504436, 0.60597474, 0.73701583, 0.95817656,
       0.74725308, 0.58658349, 0.9491182 , 0.11022706, 0.04498552,
       0.74360473, 0.3223938 , 0.31895118, 0.94428228, 0.27691984,
       0.25273582, 0.93019277, 0.62140131, 0.38708529, 0.23503253,
       0.60293592, 0.58987272, 0.91085598, 0.58505512, 0.72315333,
       0.59588448, 0.59488409, 0.24004346, 0.90183277, 0.89794356,
       0.84997945, 0.09856628, 0.4740369 , 0.12583348, 0.67591077,
       0.19417265, 0.11230232, 0.00274403, 0.43550072, 0.84731

True

In [16]:
# or:
np.all( np.logical_and((a<1), (a>=0)) )

False

___
___

# Part II: Pandas exercises

## Ex. 6
Create two Pandas series containing the same four integers: 1,2,3,4; one Series with a defined index  and a Series name and one without. Analyze them both. How do they look like, can you note the differences? Can you compare whether the two Series are identical?

In [17]:
# pip install pandas in terminal
import pandas as pd

s1 = pd.Series(range(1,5), index =['one', 'two', 'three', 'four'], name = "Defined Serie")
s1

s2 = pd.Series(range(1,5))
s2

one      1
two      2
three    3
four     4
Name: Defined Serie, dtype: int64

0    1
1    2
2    3
3    4
dtype: int64

In [18]:
# for comparing:
s1.name
s2.name

s1.index
s2.index

s1.values == s2.values
s1 == s2

'Defined Serie'

Index(['one', 'two', 'three', 'four'], dtype='object')

RangeIndex(start=0, stop=4, step=1)

array([ True,  True,  True,  True])

ValueError: Can only compare identically-labeled Series objects

## Ex. 7
Take one of the two Series created above. Let’s say you named it “a”.
a) What is the difference (if any) between executing “a[1]” and “a[1:2]” (where the second expression takes the 0-based positions from 1 to 2-1, so from 1 to 1)?

In [ ]:
s1[1]
s1[1:2]

In the first case only the element is printed while in the second the index and the name of the Serie are returned as well.

b) Now create a third Series (“c”) with the same for integers (1,2,3,4) and use as index the same integers but in inverted order (4,3,2,1). What do you get now for “c[1]” and “c[1:2]”? Can you explain the observation?

In [ ]:
c = pd.Series(range(1,5), index = range(4,0,-1))
c
c[1] # this works searching for the index with the same number
c[1:2] # this works with the automatic indeces

c) Now try “c.loc[1:2]”. You should get an empty Series. Why is that? How can you fix this? How about “c.iloc[1:2]”. Do you get what you expect?

In [ ]:
c.loc[1:2]
c.iloc[1:2]

## Ex.8
PLAY with Pandas Series! Try adding elements, removing elements, overwriting elements, etc! Try missing values! Try whatever comes into your mind and see what happens. And: read some documentation; as usual there is more to discover than what we discussed in the lecture …!

In [ ]:
c = pd.Series(range(1,5), index = range(4,0,-1))
c
c.loc[2] = 'three'
c
c.iloc[[0,1]] = 'one','two'
c
c[5] = 'zero'
c

In [ ]:
c = pd.Series(range(1,5), index = range(4,0,-1))
c[5] = 'zero'

c.drop(5, inplace = True)
c
c1 = c.drop(4)
c1
c

In [ ]:
d = pd.Series(range(1,5), index = ['a', 'b', 'c', 'd'])
d
d1 = d.truncate('b', 'c')
d1

In [ ]:
# for inserting missing values
e = pd.Series([1, 2], dtype=np.int64).reindex([0, 1, 2])
e

In [ ]:
f = pd.Series([[1, 4], [2, 3]], dtype=np.int64).reindex([0, 1, 2])
f

---
## Ex. 9
Pandas DataFrame: Create the first DataFrame “genes” that we saw in the lectures (slide 60), so that you have:
geneID chrom protein
TP53 7157 17 p53
AKT 1 207 14 Akt1
RB1 5925 13 pRb
a) Add two new columns/data items: “start_pos” and “end_pos” (look up the genes or just invent some positions). Inspect the DataFrame afterwards. Do you get what you expected?

In [19]:
indices = ['geneID', 'chrom', 'protein']

g1 = pd.Series([7157, 17, 'p53'], index = indices, name = 'TP53')
g2 = pd.Series([207, 14, 'Akt1'], index = indices, name = 'AKT1')
g3 = pd.Series([5925, 13, 'pRb'], index = indices, name = 'RB1')

genes = pd.DataFrame([g1, g2, g3])
genes

geneID  chrom protein
TP53    7157     17     p53
AKT1     207     14    Akt1
RB1     5925     13     pRb

In [20]:
genes['start_pos'] = [7668421, 104769349, 48303751]
genes['end_pos'] = [7687490, 104795748, 48481890]
genes

geneID  chrom protein  start_pos    end_pos
TP53    7157     17     p53    7668421    7687490
AKT1     207     14    Akt1  104769349  104795748
RB1     5925     13     pRb   48303751   48481890

b) Add a derived data item “length” determined from the chromosomal positions added in a)

In [21]:
genes['length'] = genes['end_pos'] - genes['start_pos'] + 1
genes

geneID  chrom protein  start_pos    end_pos  length
TP53    7157     17     p53    7668421    7687490   19070
AKT1     207     14    Akt1  104769349  104795748   26400
RB1     5925     13     pRb   48303751   48481890  178140

c) Use single command/expression to get the start position of all genes which have a chromosome number of <=14. Try to get the list of starting positions both as a Pandas Series and as a NumPy array!

In [22]:
genes['start_pos'].where(genes['chrom'] <= 14)
np.array(genes['start_pos'].where(genes['chrom'] <= 14))

TP53            NaN
AKT1    104769349.0
RB1      48303751.0
Name: start_pos, dtype: float64

array([           nan, 1.04769349e+08, 4.83037510e+07])

In [23]:
# correct form
genes[genes['chrom'] <= 14]['start_pos'] # Pandas series
genes[genes['chrom'] <= 14]['start_pos'].values # NumPy array

AKT1    104769349
RB1      48303751
Name: start_pos, dtype: int64

array([104769349,  48303751], dtype=int64)

## Ex. 10
PLAY with DataFrames! Drop rows and columns!
Try to write the data to a CSV file, etc! Read some documentation and then write the data also as TSV!
Concatenate the DataFrame with itself!
Define a second DataFrame using the same geneIDs (but partly different genes) and containing different information (e.g., gene description, biotype, etc); then merge/join the two DataFrames in different ways (inner, outer, left, right).

In [34]:
g4 = pd.Series([283989, 16, 'Tsen', 40, 500, 461], index = genes.columns, name = 'TSEN54') 
g5 = pd.Series([6868, 21, 'Adam17', 100, 3000, 2901], index = genes.columns, name = 'ADAM17') 
g6 = pd.Series([2993, 5, 'Gypa', 5400, 6000, 601], index = genes.columns, name = 'GYPA') 

other_genes = pd.DataFrame([g4, g5, g6])
other_genes

geneID  chrom protein  start_pos  end_pos  length
TSEN54  283989     16    Tsen         40      500     461
ADAM17    6868     21  Adam17        100     3000    2901
GYPA      2993      5    Gypa       5400     6000     601

In [39]:
all_genes = pd.concat([genes, other_genes])
all_genes

geneID  chrom protein  start_pos    end_pos  length
TP53      7157     17     p53    7668421    7687490   19070
AKT1       207     14    Akt1  104769349  104795748   26400
RB1       5925     13     pRb   48303751   48481890  178140
TSEN54  283989     16    Tsen         40        500     461
ADAM17    6868     21  Adam17        100       3000    2901
GYPA      2993      5    Gypa       5400       6000     601

In [40]:
pd.concat([all_genes, all_genes])

geneID  chrom protein  start_pos    end_pos  length
TP53      7157     17     p53    7668421    7687490   19070
AKT1       207     14    Akt1  104769349  104795748   26400
RB1       5925     13     pRb   48303751   48481890  178140
TSEN54  283989     16    Tsen         40        500     461
ADAM17    6868     21  Adam17        100       3000    2901
GYPA      2993      5    Gypa       5400       6000     601
TP53      7157     17     p53    7668421    7687490   19070
AKT1       207     14    Akt1  104769349  104795748   26400
RB1       5925     13     pRb   48303751   48481890  178140
TSEN54  283989     16    Tsen         40        500     461
ADAM17    6868     21  Adam17        100       3000    2901
GYPA      2993      5    Gypa       5400       6000     601

In [41]:
all_genes.drop('GYPA', inplace = True, axis = 0)

In [43]:
all_genes.drop('length', inplace = False, axis = 1)

geneID  chrom protein  start_pos    end_pos
TP53      7157     17     p53    7668421    7687490
AKT1       207     14    Akt1  104769349  104795748
RB1       5925     13     pRb   48303751   48481890
TSEN54  283989     16    Tsen         40        500
ADAM17    6868     21  Adam17        100       3000

- .csv file

In [44]:
all_genes = pd.concat([genes, other_genes])
all_genes.to_csv("all_genes.csv")

In [53]:
df = pd.read_csv("all_genes.csv", index_col = 'Unnamed: 0')
df

geneID  chrom protein  start_pos    end_pos  length
TP53      7157     17     p53    7668421    7687490   19070
AKT1       207     14    Akt1  104769349  104795748   26400
RB1       5925     13     pRb   48303751   48481890  178140
TSEN54  283989     16    Tsen         40        500     461
ADAM17    6868     21  Adam17        100       3000    2901
GYPA      2993      5    Gypa       5400       6000     601

- .tsv file

In [51]:
all_genes.to_csv("all_genes.tsv", sep = '\t', header = 0)

In [52]:
tabs = pd.read_csv('all_genes.tsv', sep = '\t', header = 0)
tabs

TP53    7157  17     p53    7668421    7687490   19070
0    AKT1     207  14    Akt1  104769349  104795748   26400
1     RB1    5925  13     pRb   48303751   48481890  178140
2  TSEN54  283989  16    Tsen         40        500     461
3  ADAM17    6868  21  Adam17        100       3000    2901
4    GYPA    2993   5    Gypa       5400       6000     601

In [55]:
other_indices = ['geneID', 'description', 'biotype']

g7 = pd.Series([7157, 'can cause tumor if modified', 'hum'], index = other_indices, name = 'TP53')
g8 = pd.Series([207, 'boh', 'dog'], index = other_indices, name = 'AKT1')
g9 = pd.Series([5925, 'rhythm and blues', 'cat'], index = other_indices, name = 'RB1')

fake_genes = pd.DataFrame([g7, g8, g9])
fake_genes

geneID                  description biotype
TP53    7157  can cause tumor if modified     hum
AKT1     207                          boh     dog
RB1     5925             rhythm and blues     cat

In [56]:
shitty_genes = genes.merge(fake_genes, 
                           left_on = 'geneID', 
                           right_on= 'geneID',
                           how = 'inner')
shitty_genes

geneID  chrom protein  start_pos    end_pos  length  \
0    7157     17     p53    7668421    7687490   19070   
1     207     14    Akt1  104769349  104795748   26400   
2    5925     13     pRb   48303751   48481890  178140   

                   description biotype  
0  can cause tumor if modified     hum  
1                          boh     dog  
2             rhythm and blues     cat

---
---
# SeaBorn

---